import { useState } from 'react'
import './HomePage.css'

function HomePage({ onCategorySelect }) {
  const [searchQuery, setSearchQuery] = useState('')
  const [showAbout, setShowAbout] = useState(false)
  const [showFunFacts, setShowFunFacts] = useState(false)
  const [showMenu, setShowMenu] = useState(false)
  
  const funFacts = [
    "🧠 Your brain uses about 20% of your body's total energy, despite being only 2% of your body weight!",
    "🌍 There are more possible games of chess than there are atoms in the observable universe.",
    "🐙 Octopuses have three hearts and blue blood, making them truly alien-like creatures!",
    "🌱 A single tree can absorb up to 48 pounds of CO2 per year and produce enough oxygen for two people.",
    "⭐ The light from some stars we see tonight started its journey before humans existed on Earth.",
    "🧬 You share about 60% of your DNA with bananas - we're more connected to nature than we think!",
    "🌊 The ocean produces over 70% of Earth's oxygen, not trees as commonly believed.",
    "🦋 Butterflies taste with their feet and smell with their antennae.",
    "💫 Honey never spoils - archaeologists have found edible honey in ancient Egyptian tombs!",
    "🎵 Music can trigger the release of dopamine, the same chemical released when eating or falling in love."
  ]
  

  
  const categories = [
    {
      id: 'wellness',
      name: 'Wellness',
      icon: '🌿',
      description: 'General health and wellbeing topics'
    },
    {
      id: 'tech',
      name: 'Tech',
      icon: '💻',
      description: 'Technology, programming, and digital topics'
    },
    {
      id: 'productivity',
      name: 'Productivity',
      icon: '⚡',
      description: 'Time management and efficiency tips'
    },
    {
      id: 'nutrition',
      name: 'Nutrition',
      icon: '🥗',
      description: 'Food, diet, and healthy eating'
    },
    {
      id: 'fitness',
      name: 'Fitness',
      icon: '💪',
      description: 'Exercise, workouts, and physical health'
    },
    {
      id: 'mental-wellness',
      name: 'Mental Wellness',
      icon: '🧠',
      description: 'Mental health and mindfulness'
    }
  ]

  const handleCategoryClick = (category) => {
    onCategorySelect(category)
  }

  const handleSearchSubmit = (e) => {
    e.preventDefault()
    if (searchQuery.trim()) {
      // Navigate to quiz generator with custom topic
      const topicName = searchQuery.trim()
      onCategorySelect({
        id: 'custom',
        name: topicName.charAt(0).toUpperCase() + topicName.slice(1), // Capitalize first letter
        icon: '🔍', // Search icon for custom topics
        topic: topicName
      })
    }
  }

  return (
    <div className="homepage">
      {showAbout && (
        <>
          <div className="modal-backdrop" onClick={() => setShowAbout(false)}></div>
          <div className="modal-section">
            <button className="close-btn" onClick={() => setShowAbout(false)}>×</button>
            <h2>About Us</h2>
            <p>Welcome to your smart AI-powered quiz companion! Here, quizzes aren't just static questions—they're dynamically generated by cutting-edge AI to challenge your brain, sharpen your skills, and make learning fun.</p>
            <p>Whether you're a student, a lifelong learner, or just love testing your knowledge, our platform adapts to your pace, creates engaging questions, and provides instant feedback. Behind the scenes, advanced AI models analyze topics and generate quizzes tailored to your interests, ensuring every session is unique.</p>
            <p>Join us to explore, learn, and level up—one smart quiz at a time!</p>
          </div>
        </>
      )}

      {showFunFacts && (
        <>
          <div className="modal-backdrop" onClick={() => setShowFunFacts(false)}></div>
          <div className="modal-section">
            <button className="close-btn" onClick={() => setShowFunFacts(false)}>×</button>
            <h2>🎯 Fun Facts to Spark Your Curiosity</h2>
            <div className="fun-facts-modal-grid">
              {funFacts.map((fact, index) => (
                <div key={index} className="fun-fact-modal-card">
                  <p>{fact}</p>
                </div>
              ))}
            </div>
          </div>
        </>
      )}

      <div className="menu-section">
        <div className="menu-controls">
          <button 
            className="menu-btn"
            onClick={() => setShowMenu(!showMenu)}
          >
            ☰
          </button>
          {showMenu && (
            <div className="dropdown-menu">
              <button 
                className="menu-item"
                onClick={() => {
                  setShowAbout(true)
                  setShowMenu(false)
                }}
              >
                About Us
              </button>
              <button 
                className="menu-item"
                onClick={() => {
                  setShowFunFacts(true)
                  setShowMenu(false)
                }}
              >
                Fun Facts
              </button>
            </div>
          )}
        </div>
      </div>

      <div className="logo-section">
        <div className="logo-container">
          <img src="/public/logo.png" alt="Logo" className="homepage-logo" />
        </div>
      </div>

      <div className="homepage-header">
        <form className="search-form" onSubmit={handleSearchSubmit}>
          <div className="search-container">
            <input
              type="text"
              placeholder="Or search for any topic..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="search-input"
            />
            <button type="submit" className="search-button">
              🔍
            </button>
          </div>
        </form>
      </div>

      <div className="categories-grid">
        {categories.map((category) => (
          <div
            key={category.id}
            className="category-card"
            onClick={() => handleCategoryClick(category)}
          >
            <div className="category-icon">
              {category.icon}
            </div>
            <h3 className="category-name">{category.name}</h3>
            <p className="category-description">{category.description}</p>
          </div>
        ))}
      </div>
    </div>
  )
}

export default HomePage